# Generated by Django 4.2.5 on 2023-09-26 06:17

from django.db import migrations, models
import robots.validators


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robot',
            name='model',
            field=models.CharField(max_length=2, validators=[robots.validators.validate_length]),
        ),
        migrations.AlterField(
            model_name='robot',
            name='serial',
            field=models.CharField(blank=True, max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='robot',
            name='version',
            field=models.CharField(max_length=2, validators=[robots.validators.validate_length]),
        ),
    ]
