# Generated by Django 4.2.5 on 2023-09-26 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0003_remove_robot_id_robot_robot_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robot',
            name='robot_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
