# Generated by Django 4.2.5 on 2023-09-26 08:04

from django.db import migrations, models
import django.db.models.deletion
import robots.validators


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0004_alter_robot_robot_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='RobotModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2, validators=[robots.validators.validate_length])),
            ],
        ),
        migrations.AlterField(
            model_name='robot',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robots.robotmodel'),
        ),
    ]
