# Generated by Django 4.2.5 on 2023-09-26 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0005_robotmodel_alter_robot_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='robot',
            old_name='robot_id',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='robotmodel',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
