# Generated by Django 4.2.5 on 2023-09-27 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0006_rename_robot_id_robot_id_alter_robotmodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robot',
            name='serial',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
