# Generated by Django 4.2.5 on 2023-09-27 07:54

from django.db import migrations, models
import robots.validators


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0007_alter_robot_serial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robotmodel',
            name='name',
            field=models.CharField(max_length=2, unique=True, validators=[robots.validators.validate_length]),
        ),
    ]
